baseURL = "https://imdesign.netlify.app/"
languageCode = "en-us"
summaryLength = "10"
theme = "icelab-hugo"
title = "I.M. Design"
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
URL = "about"
hasChildren = true
name = "About"
weight = 1
[[menu.main]]
URL = "works"
hasChildren = true
name = "Works"
weight = 2
[[menu.main]]
URL = "contact"
hasChildren = true
name = "Contact"
weight = 3
[outputs]
home = ["HTML", "RSS"]
[params]
author = "Themefisher"
contact_form_action = "#"
description = "This is meta description"
footer_content = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus sint magnam quia doloremque."
home = "Home"
logo = "images/logo.png"
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyAMxZLJVnjXX4vmC15AXbkuqKn-PO8qovY"
map_latitude = "44.439973674502525"
map_longitude = "26.113690644176366"
map_marker = "images/marker.png"
[[params.plugins.js]]
URL = "plugins/plugins.js"
[[params.social]]
icon = "fa-facebook"
link = "#"
name = "facebook"
[[params.social]]
icon = "fa-twitter"
link = "#"
name = "twitter"
[[params.social]]
icon = "fa-instagram"
link = "#"
name = "instagram"
